# Generated by Django 5.0.6 on 2024-09-21 15:10

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/static/images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=400, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=1000)),
                ('message', models.CharField(max_length=3000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=300, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=300, verbose_name='lastname')),
                ('phone', models.CharField(max_length=300, verbose_name='phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_info', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', django_jalali.db.models.jDateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('total_price', models.FloatField(verbose_name='totalPrice')),
                ('total_discount', models.FloatField(verbose_name='totalDiscount')),
                ('delivery_address_unit_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='unitNumber')),
                ('delivery_address_street_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='streetName')),
                ('delivery_address_suburb', models.CharField(blank=True, max_length=200, null=True, verbose_name='suburb')),
                ('delivery_address_city', models.CharField(blank=True, max_length=200, null=True, verbose_name='city')),
                ('delivery_address_state', models.CharField(blank=True, max_length=200, null=True, verbose_name='state')),
                ('delivery_address_country', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_postcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='postCode')),
                ('mobile_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='mobileNumber')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_authority', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED')], default='registered', max_length=200, verbose_name='status')),
                ('tracking_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='trackingNumber')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='store.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='productName')),
                ('productCode', models.CharField(blank=True, max_length=500, verbose_name='productCode')),
                ('image', models.ImageField(default='', upload_to='media/static/images/', verbose_name='Image')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('material', models.CharField(blank=True, max_length=200, null=True, verbose_name='material')),
                ('madeIn', models.CharField(blank=True, max_length=200, null=True, verbose_name='madeIn')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('isactive', models.BooleanField(default=True, verbose_name='isactive')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='media/static/images/', verbose_name='Images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='size')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_price', models.FloatField(verbose_name='totalPrice')),
                ('variation_price', models.FloatField()),
                ('discount', models.FloatField(verbose_name='discount')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('variation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='store.productvariation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('store_name', models.CharField(max_length=400, verbose_name='Storename')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('instagramId', models.CharField(max_length=400, verbose_name='InstagramId')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', models.CharField(blank=True, max_length=20, verbose_name='Contact')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Address')),
                ('image', models.ImageField(default='', upload_to='media/static/images/', verbose_name='Image')),
                ('delivery_cost', models.IntegerField(default=0, verbose_name='delivery-cost')),
                ('banner_image1', models.ImageField(default='', upload_to='media/static/images/', verbose_name='banner-Image1')),
                ('banner_image2', models.ImageField(default='', upload_to='media/static/images/', verbose_name='banner-Image2')),
                ('banner_image3', models.ImageField(default='', upload_to='media/static/images/', verbose_name='banner-Image3')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shop', verbose_name='shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='store.shop', verbose_name='shop'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('bankName', models.CharField(default='', max_length=200, verbose_name='bankName')),
                ('cartNumber', models.CharField(default='', max_length=200, verbose_name='cartNumber')),
                ('accountNumber', models.CharField(default='', max_length=200, verbose_name='accountNumber')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subname', models.CharField(max_length=200, verbose_name='Subcategory')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/static/images/')),
                ('categoryname', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.subcategory', verbose_name='subcategory'),
        ),
    ]
