# Generated by Django 5.0.6 on 2024-11-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='store_name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Storename'),
        ),
    ]
