# Generated by Django 5.0.6 on 2024-10-08 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 14, 28, 30, 547315, tzinfo=datetime.timezone.utc)),
        ),
    ]
