# Generated by Django 5.0.6 on 2024-12-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
