# Generated by Django 5.0.6 on 2024-09-22 06:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('instagram_user_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.TextField()),
                ('token_expiry', models.DateTimeField(default=datetime.datetime(2024, 11, 21, 6, 48, 48, 950044, tzinfo=datetime.timezone.utc))),
                ('last_authenticated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_auth', to='store.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
