# Generated by Django 5.0.6 on 2024-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_title_alter_subcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopimage',
            name='banner_image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='banner-Image1'),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='banner_image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='banner-Image2'),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='banner_image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='banner-Image3'),
        ),
    ]
