# Generated by Django 5.0.6 on 2024-09-22 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shopauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 8, 50, 0, 946506, tzinfo=datetime.timezone.utc)),
        ),
    ]
