# Generated by Django 5.0.6 on 2024-11-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shop_account_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='store_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Storename'),
        ),
    ]
