# Generated by Django 5.0.6 on 2024-12-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shopimage_banner_image1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountInfo',
        ),
    ]
