# Generated by Django 5.0.6 on 2024-09-22 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_instagram_post_alter_shopauth_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instagram_post',
            field=models.BooleanField(default=False, verbose_name='Post to Instagram'),
        ),
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 9, 23, 57, 439374, tzinfo=datetime.timezone.utc)),
        ),
    ]
