# Generated by Django 4.2.1 on 2023-09-05 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_aboutus_is_deleted_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bankName', models.CharField(max_length=200)),
                ('cartNumber', models.CharField(max_length=200)),
                ('accountNumber', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('productCode', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterdOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('orderCode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nameCode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.productcode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantityInStore',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='sentOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('postCode', models.CharField(max_length=400)),
                ('registerdOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.registerdorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='financialReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('registerdOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.registerdorder')),
                ('sentOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sentorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='nameCode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.productcode'),
        ),
    ]
