# Generated by Django 5.0.6 on 2024-10-08 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shopauth_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 14, 40, 10, 115611, tzinfo=datetime.timezone.utc)),
        ),
    ]
