# Generated by Django 5.0.6 on 2024-12-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_accountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
