# Generated by Django 5.0.6 on 2024-11-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shop_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='phone',
        ),
    ]
