# Generated by Django 4.2.1 on 2023-09-05 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bankaccount_productcode_registerdorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nameCode',
        ),
        migrations.RemoveField(
            model_name='registerdorder',
            name='nameCode',
        ),
        migrations.AddField(
            model_name='product',
            name='codeProduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='code_product', to='store.productcode'),
        ),
        migrations.AddField(
            model_name='product',
            name='nameProduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='name_product', to='store.productcode'),
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='codeProduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='code_product_order', to='store.productcode'),
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='nameProduct',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='name_product_order', to='store.productcode'),
        ),
    ]
