# Generated by Django 5.0.6 on 2024-09-26 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_instagram_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram_post_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 8, 24, 39, 700585, tzinfo=datetime.timezone.utc)),
        ),
    ]
