# Generated by Django 5.0.6 on 2024-09-30 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_instagram_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 11, 4, 39, 225110, tzinfo=datetime.timezone.utc)),
        ),
    ]
