# Generated by Django 4.2.1 on 2023-09-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_namecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='codeProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nameProduct',
        ),
        migrations.RemoveField(
            model_name='registerdorder',
            name='codeProduct',
        ),
        migrations.RemoveField(
            model_name='registerdorder',
            name='nameProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='productCode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_code', to='store.productcode'),
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='productCode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_code_order', to='store.productcode'),
        ),
    ]
