# Generated by Django 5.0.6 on 2024-12-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_webp_image_productimage_webp_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color', verbose_name='color'),
        ),
    ]
