# Generated by Django 5.0.6 on 2024-10-07 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_shopauth_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 8, 52, 11, 750995, tzinfo=datetime.timezone.utc)),
        ),
    ]
