# Generated by Django 4.2.1 on 2023-09-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_codeproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdorder',
            name='productCode',
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='orderDetails',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='store.product'),
        ),
    ]
