# Generated by Django 4.2.1 on 2023-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_registerdorder_productcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdorder',
            name='deliveryCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='finalPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='quantiy',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantityInStore',
            field=models.IntegerField(default=0),
        ),
    ]
