# Generated by Django 5.0.6 on 2024-10-08 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_slug_shop_slug_alter_shopauth_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 15, 45, 1, 874454, tzinfo=datetime.timezone.utc)),
        ),
    ]
