# Generated by Django 4.2.1 on 2023-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_registerdorder_deliverycost_registerdorder_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdorder',
            name='quantiy',
        ),
        migrations.AddField(
            model_name='registerdorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registerdorder',
            name='discount',
            field=models.FloatField(default=1),
        ),
    ]
