# Generated by Django 5.0.6 on 2024-11-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
