# Generated by Django 5.0.6 on 2024-10-09 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_shop_slug_alter_shopauth_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='instagram_post',
        ),
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 6, 2, 28, 332185, tzinfo=datetime.timezone.utc)),
        ),
    ]
