# Generated by Django 5.0.6 on 2024-10-10 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_instagram_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 7, 28, 31, 224228, tzinfo=datetime.timezone.utc)),
        ),
    ]
