# Generated by Django 5.0.6 on 2024-11-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_blog_seo_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
