# Generated by Django 5.0.6 on 2024-10-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_shopauth_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopauth',
            name='token_expiry',
            field=models.DateTimeField(),
        ),
    ]
