# Generated by Django 5.0.6 on 2024-12-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_category_seo_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='banner_image1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='banner_image2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='banner_image3',
        ),
        migrations.AlterField(
            model_name='otp',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=15, verbose_name='mobilenumber'),
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('banner_image1', models.ImageField(default='', upload_to='images/', verbose_name='banner-Image1')),
                ('banner_image2', models.ImageField(default='', upload_to='images/', verbose_name='banner-Image2')),
                ('banner_image3', models.ImageField(default='', upload_to='images/', verbose_name='banner-Image3')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_images', to='store.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
