# Generated by Django 4.2.1 on 2023-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_subcategory_alter_subcategory_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
