# Generated by Django 4.2.1 on 2023-09-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('size', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.productcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
