# Generated by Django 4.2.1 on 2023-09-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
    ]
