# Generated by Django 4.2.1 on 2023-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_color_remove_product_colors_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='color',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
