# Generated by Django 4.2.1 on 2023-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_quantity_color_delete_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='size',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
