# Generated by Django 4.2.1 on 2023-09-17 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_quantity_size_delete_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='store.quantity'),
        ),
    ]
