# Generated by Django 4.2.1 on 2023-09-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='store.quantity'),
        ),
    ]
