# Generated by Django 5.0.6 on 2024-11-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_total_discount_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delivery_policy',
            field=models.TextField(blank=True, verbose_name='delivery-policy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount'),
        ),
    ]
