# Generated by Django 4.2.1 on 2023-09-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
