# Generated by Django 4.2.1 on 2023-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_color_alter_quantity_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AlterField(
            model_name='quantity',
            name='color',
            field=models.CharField(default='', max_length=400),
        ),
    ]
