# Generated by Django 4.2.1 on 2023-09-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_color_alter_quantity_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.color'),
        ),
    ]
