# Generated by Django 4.2.1 on 2023-09-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_quantity_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='color',
        ),
        migrations.AddField(
            model_name='quantity',
            name='colors',
            field=models.ManyToManyField(to='store.color'),
        ),
    ]
