# Generated by Django 4.2.5 on 2024-03-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_quantity_color_quantity_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='name',
            new_name='store_name',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='category',
        ),
    ]
