# Generated by Django 4.2.5 on 2024-03-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
