# Generated by Django 4.2.5 on 2024-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='media/static/images/'),
        ),
    ]
