# Generated by Django 4.2.5 on 2024-04-04 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0032_shop_delete_aboutus_product_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
                ('total_discount', models.FloatField()),
                ('delivery_address_unit_number', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_street_number', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_street_name', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_city', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_state', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_country', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address_postcode', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('DISPATCHED', 'Dispatched'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered')], max_length=200)),
                ('tracking_number', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='store.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('variation_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('size', models.CharField(default='', max_length=400)),
                ('quantity', models.IntegerField(default=0)),
                ('colors', models.ManyToManyField(to='store.color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='registerdorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sentorder',
            name='registerdOrder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantities',
        ),
        migrations.DeleteModel(
            name='financialReport',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.DeleteModel(
            name='RegisterdOrder',
        ),
        migrations.DeleteModel(
            name='sentOrder',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='store.productvariation'),
        ),
    ]
