# Generated by Django 4.2.5 on 2024-04-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_order_orderdelivery_orderitem_productvariation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCode',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='ProductCode',
        ),
    ]
