# Generated by Django 4.2.5 on 2024-04-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_name_alter_product_productcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='colors',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color'),
        ),
    ]
