# Generated by Django 5.0.6 on 2024-05-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.CreateModel(
            name='item_quantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_quantity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.item_quantity'),
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
