# Generated by Django 5.0.4 on 2024-05-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_product_images_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image',
        ),
    ]
