# Generated by Django 5.0.6 on 2024-05-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_rename_image_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
