# Generated by Django 5.0.6 on 2024-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_rename_images_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='item_quantity',
        ),
    ]
