# Generated by Django 5.0.6 on 2024-05-31 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_bankaccount_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='accountNumber',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bankName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='cartNumber',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
