# Generated by Django 5.0.6 on 2024-06-10 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_remove_bankaccount_account_bankaccount_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.shop'),
        ),
    ]
