# Generated by Django 5.0.6 on 2024-06-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_bankaccount_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
