# Generated by Django 5.0.6 on 2024-06-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_productvariation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='', upload_to='media/static/images/'),
        ),
    ]
