# Generated by Django 5.0.6 on 2024-06-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/'),
        ),
    ]
