# Generated by Django 5.0.6 on 2024-07-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_remove_order_delivery_address_street_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagramId',
            field=models.URLField(verbose_name='InstagramId'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='store_name',
            field=models.CharField(max_length=400, verbose_name='Storename'),
        ),
    ]
