# Generated by Django 5.0.6 on 2024-07-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_category_image_alter_bankaccount_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bankName',
            field=models.CharField(default='', max_length=200, verbose_name='bankName'),
        ),
    ]
