# Generated by Django 5.0.6 on 2024-07-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_alter_bankaccount_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
