# Generated by Django 5.0.6 on 2024-07-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_product_is_approved_productimage_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
