# Generated by Django 5.0.6 on 2024-07-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_shop_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_approved',
        ),
    ]
