# Generated by Django 5.0.6 on 2024-08-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_delete_payment_order_payment_authority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='', upload_to='media/static/images/', verbose_name='Image'),
        ),
    ]
