# Generated by Django 5.0.6 on 2024-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='', upload_to='media/static/images/', verbose_name='Image'),
        ),
    ]
