# Generated by Django 5.0.6 on 2024-08-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='instagramId',
            field=models.CharField(max_length=400, verbose_name='InstagramId'),
        ),
    ]
