# Generated by Django 5.0.6 on 2024-08-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_alter_shop_instagramid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variation_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('VARIATION', 'Variation')], default='VARIATION', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='size'),
        ),
    ]
