# Generated by Django 5.0.6 on 2024-08-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_productvariation_variation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='variation_type',
        ),
    ]
