# Generated by Django 5.0.6 on 2024-08-15 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_alter_product_description_alter_product_madein_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered')], default='registered', max_length=200, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=300, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=300, verbose_name='lastname')),
                ('phone', models.CharField(max_length=300, verbose_name='phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_info', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
