# Generated by Django 5.0.6 on 2024-08-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED')], default='registered', max_length=200, verbose_name='status'),
        ),
    ]
