# Generated by Django 5.0.6 on 2024-08-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_alter_accountinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=1000)),
                ('message', models.CharField(max_length=3000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
