# Generated by Django 5.0.6 on 2024-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCode',
            field=models.CharField(blank=True, max_length=500, verbose_name='productCode'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
