services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5      

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - celery
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
      - redis

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
