# Generated by Django 5.0.6 on 2024-12-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='', max_length=300, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='', max_length=300, verbose_name='lastname'),
        ),
    ]
